# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ master ]

env:
  ARTIFACTORY_URL: https://jfrog.madness.games/artifactory
  VAULT_URL: https://vault.madness.games

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ env.VAULT_URL }}
          method: approle
          roleId: ${{ secrets.GTA_VAULT_ROLEID }}
          secretId: ${{ secrets.GTA_VAULT_SECRETID }}
          secrets: |
            jenkins/jfrog/service-accounts/ci username ;
            jenkins/jfrog/service-accounts/ci password

      - name: Run checkstyle and tests with Gradle
        run: |
          ./gradlew clean check \
          -Partifactory \
          -Partifactory_context_url=${{ env.ARTIFACTORY_URL }} \
          -Partifactory_repo_key=libs-release \
          -Partifactory_user=${{ steps.vault.outputs.username }} \
          -Partifactory_password=${{ steps.vault.outputs.password }}
